projects_url: https://mstn.github.io

nav:
  home: /
  articles: /archives/

social_links:
  github: https://github.com/mstn
  mail: mailto:mstn@posteo.org

tags_overview: true

copyright:
  start_year: 2018
  end_year:

logo:
  enabled: false
  width: 50
  height: 50
  url: /images/logo.png
  gravatar: false
  grayout: true

colorscheme: white

rss: true

mathjax:
  enabled: true

cdn:
  enable: false