#
# Customization for [cactus theme](https://github.com/probberechts/hexo-theme-cactus) 
# commit 7a6074d830ac5d524582f142ac524c041077aad7
#
projects_url: https://mstn.github.io

nav:
  home: /
  articles: /archives/

posts_overview:
  show_all_posts: true

social_links:
  - icon: github
    link: /
  - icon: mail
    link: mailto:mstn@posteo.org

tags_overview: false

copyright:
  start_year: 2018
  end_year:

logo:
  enabled: false
  width: 50
  height: 50
  url: /images/logo.png
  gravatar: false
  grayout: true

colorscheme: white

rss: true

mathjax:
  enabled: true

cdn:
  enable: false